version: '3.4'

networks: 
  eshop: 
    external: true

services:
  rediscache:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - C:\MyData\eshop\Redis:/data
    networks: 
      - eshop

  cart:
    image: ${REGISTRY:-cart}/api:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: Cart/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - REDIS_CONFIG=rediscache:6379,abortConnect=False,password=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81,ssl=False
    depends_on: 
      - rediscache
    networks: 
      - eshop
